create DATABASE hospital_db;

use hospital_db;

CREATE TABLE `cargos` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `Designacao` VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE `utilizador` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `Username` VARCHAR(80) UNIQUE NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Cargos` INTEGER NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) UNIQUE,
  `Telefone` VARCHAR(20),
  `DataCriacao` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE `stock` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `Nome` VARCHAR(100) UNIQUE NOT NULL,
  `Quantidade` INTEGER NOT NULL DEFAULT 0,
  `QuantidadeMinima` INTEGER NOT NULL DEFAULT 5,
  `Descricao` VARCHAR(200)
);

CREATE TABLE `reportados_stock` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `IdStock` INTEGER NOT NULL,
  `IdReporter` INTEGER,
  `DataReporte` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `QuantidadeAtual` INTEGER NOT NULL,
  `Descricao` VARCHAR(300),
  `Estado` VARCHAR(30) NOT NULL DEFAULT 'Pendente'
);

CREATE TABLE `avarias` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `IdReporter` INTEGER NOT NULL,
  `DataReporte` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `Descricao` VARCHAR(500) NOT NULL,
  `Localizacao` VARCHAR(100),
  `Estado` VARCHAR(30) NOT NULL DEFAULT 'Pendente',
  `IdTecnico` INTEGER
);

CREATE TABLE `consultas` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `IdUtente` INTEGER NOT NULL,
  `IdMedico` INTEGER NOT NULL,
  `TipoConsulta` VARCHAR(50) NOT NULL,
  `Estado` VARCHAR(30) NOT NULL DEFAULT 'Marcada',
  `Observacoes` VARCHAR(500)
);

CREATE TABLE `cirurgias` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `IdUtente` INTEGER NOT NULL,
  `IdCirurgiaoPrincipal` INTEGER NOT NULL,
  `DuracaoEstimada` INTEGER NOT NULL,
  `TipoCirurgia` VARCHAR(100) NOT NULL,
  `Estado` VARCHAR(30) NOT NULL DEFAULT 'Marcada',
  `Observacoes` VARCHAR(500)
);

CREATE TABLE `assistentes_cirurgia` (
  `IdCirurgia` INTEGER NOT NULL,
  `IdMedico` INTEGER NOT NULL,
  PRIMARY KEY (`IdCirurgia`, `IdMedico`)
);

CREATE TABLE `receitas` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `IdUtente` INTEGER NOT NULL,
  `IdConsulta` INTEGER NOT NULL,
  `Receita` VARCHAR(400) NOT NULL,
  `Observacoes` VARCHAR(400),
  `DataInicio` DATE NOT NULL,
  `DataFim` DATE
);

CREATE TABLE `mensagens` (
  `Id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `IdRemetente` INTEGER NOT NULL,
  `IdDestinatario` INTEGER NOT NULL,
  `DataEnvio` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `Conteudo` TEXT NOT NULL,
  `Lida` BOOLEAN NOT NULL DEFAULT false
);

ALTER TABLE `utilizador` ADD FOREIGN KEY (`Cargos`) REFERENCES `cargos` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `reportados_stock` ADD FOREIGN KEY (`IdStock`) REFERENCES `stock` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `reportados_stock` ADD FOREIGN KEY (`IdReporter`) REFERENCES `utilizador` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `avarias` ADD FOREIGN KEY (`IdReporter`) REFERENCES `utilizador` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `avarias` ADD FOREIGN KEY (`IdTecnico`) REFERENCES `utilizador` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `consultas` ADD FOREIGN KEY (`IdUtente`) REFERENCES `utilizador` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `consultas` ADD FOREIGN KEY (`IdMedico`) REFERENCES `utilizador` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `cirurgias` ADD FOREIGN KEY (`IdUtente`) REFERENCES `utilizador` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `cirurgias` ADD FOREIGN KEY (`IdCirurgiaoPrincipal`) REFERENCES `utilizador` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `assistentes_cirurgia` ADD FOREIGN KEY (`IdCirurgia`) REFERENCES `cirurgias` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `assistentes_cirurgia` ADD FOREIGN KEY (`IdMedico`) REFERENCES `utilizador` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `receitas` ADD FOREIGN KEY (`IdUtente`) REFERENCES `utilizador` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `receitas` ADD FOREIGN KEY (`IdConsulta`) REFERENCES `consultas` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `mensagens` ADD FOREIGN KEY (`IdRemetente`) REFERENCES `utilizador` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `mensagens` ADD FOREIGN KEY (`IdDestinatario`) REFERENCES `utilizador` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

