# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Utentes/utente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black;\n"
"    border-radius: 10px;       \n"
"    border: 2px solid #366abf;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #366abf;\n"
"}\n"
"\n"
"QDateTimeEdit{\n"
"background-color:white; \n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QTableView{\n"
" border: 2px solid #366abf; /* Espessura, Estilo (solid/dashed/dotted) e Cor */\n"
"    border-radius: 5px;       /* Cantos arredondados */\n"
"    gridline-color: #dcdcdc;   /* Cor das linhas que separam as células */\n"
"    background-color: white;\n"
"    selection-background-color: lightblue; /* Cor da linha quando selecionada */\n"
"}\n"
"\n"
"QLCDNumber{\n"
"border: 2px solid #366abf;\n"
"border-radius: 10px;\n"
"}\n"
"QWidget{\n"
"background-color: white;\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.RelogioLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.RelogioLCD.setGeometry(QtCore.QRect(710, 20, 64, 23))
        self.RelogioLCD.setStyleSheet("")
        self.RelogioLCD.setObjectName("RelogioLCD")
        self.label_Consultas = QtWidgets.QLabel(self.centralwidget)
        self.label_Consultas.setGeometry(QtCore.QRect(20, 150, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_Consultas.setFont(font)
        self.label_Consultas.setStyleSheet("")
        self.label_Consultas.setObjectName("label_Consultas")
        self.pushButton_Receitas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Receitas.setGeometry(QtCore.QRect(660, 190, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Receitas.setFont(font)
        self.pushButton_Receitas.setStyleSheet("")
        self.pushButton_Receitas.setObjectName("pushButton_Receitas")
        self.tableView_Consultas = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Consultas.setGeometry(QtCore.QRect(20, 190, 631, 301))
        self.tableView_Consultas.setStyleSheet("")
        self.tableView_Consultas.setObjectName("tableView_Consultas")
        self.pushButton_ConsultasHoje = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ConsultasHoje.setGeometry(QtCore.QRect(660, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ConsultasHoje.setFont(font)
        self.pushButton_ConsultasHoje.setStyleSheet("")
        self.pushButton_ConsultasHoje.setObjectName("pushButton_ConsultasHoje")
        self.label_NomeUtilizador = QtWidgets.QLabel(self.centralwidget)
        self.label_NomeUtilizador.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_NomeUtilizador.setFont(font)
        self.label_NomeUtilizador.setStyleSheet("")
        self.label_NomeUtilizador.setObjectName("label_NomeUtilizador")
        self.pushButton_TodasConsultas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TodasConsultas.setGeometry(QtCore.QRect(660, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TodasConsultas.setFont(font)
        self.pushButton_TodasConsultas.setStyleSheet("")
        self.pushButton_TodasConsultas.setObjectName("pushButton_TodasConsultas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Consultas.setText(_translate("MainWindow", "Consultas de Hoje :"))
        self.pushButton_Receitas.setText(_translate("MainWindow", "Receitas"))
        self.pushButton_ConsultasHoje.setText(_translate("MainWindow", "Consultas de hoje"))
        self.label_NomeUtilizador.setText(_translate("MainWindow", "Nome"))
        self.pushButton_TodasConsultas.setText(_translate("MainWindow", "Todas as Consultas"))
