# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/medicos/Medicos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Medicos(object):
    def setupUi(self, MainWindow_Medicos):
        MainWindow_Medicos.setObjectName("MainWindow_Medicos")
        MainWindow_Medicos.resize(800, 598)
        MainWindow_Medicos.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow_Medicos)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black;\n"
"    border-radius: 10px;       \n"
"    border: 2px solid #366abf;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #366abf;\n"
"}\n"
"\n"
"QDateTimeEdit{\n"
"background-color:white; \n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QTableView{\n"
" border: 2px solid #366abf; /* Espessura, Estilo (solid/dashed/dotted) e Cor */\n"
"    border-radius: 5px;       /* Cantos arredondados */\n"
"    gridline-color: #dcdcdc;   /* Cor das linhas que separam as células */\n"
"    background-color: white;\n"
"    selection-background-color: lightblue; /* Cor da linha quando selecionada */\n"
"}\n"
"\n"
"QLCDNumber{\n"
"border: 2px solid #366abf;\n"
"border-radius: 10px;\n"
"}\n"
"QWidget{\n"
"background-color: white;\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tableView_Consultas = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Consultas.setGeometry(QtCore.QRect(20, 190, 631, 301))
        self.tableView_Consultas.setStyleSheet("")
        self.tableView_Consultas.setObjectName("tableView_Consultas")
        self.RelogioLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.RelogioLCD.setGeometry(QtCore.QRect(710, 20, 64, 23))
        self.RelogioLCD.setStyleSheet("")
        self.RelogioLCD.setObjectName("RelogioLCD")
        self.label_NomeUtilizador = QtWidgets.QLabel(self.centralwidget)
        self.label_NomeUtilizador.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_NomeUtilizador.setFont(font)
        self.label_NomeUtilizador.setStyleSheet("")
        self.label_NomeUtilizador.setObjectName("label_NomeUtilizador")
        self.label_Consultas = QtWidgets.QLabel(self.centralwidget)
        self.label_Consultas.setGeometry(QtCore.QRect(20, 150, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_Consultas.setFont(font)
        self.label_Consultas.setStyleSheet("")
        self.label_Consultas.setObjectName("label_Consultas")
        self.pushButton_ConcluirConsulta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ConcluirConsulta.setGeometry(QtCore.QRect(660, 190, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ConcluirConsulta.setFont(font)
        self.pushButton_ConcluirConsulta.setStyleSheet("")
        self.pushButton_ConcluirConsulta.setObjectName("pushButton_ConcluirConsulta")
        self.pushButton_AdiarConsulta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AdiarConsulta.setGeometry(QtCore.QRect(660, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_AdiarConsulta.setFont(font)
        self.pushButton_AdiarConsulta.setStyleSheet("")
        self.pushButton_AdiarConsulta.setObjectName("pushButton_AdiarConsulta")
        self.pushButton_RemoverConsulta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RemoverConsulta.setGeometry(QtCore.QRect(660, 310, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RemoverConsulta.setFont(font)
        self.pushButton_RemoverConsulta.setStyleSheet("")
        self.pushButton_RemoverConsulta.setObjectName("pushButton_RemoverConsulta")
        self.pushButton_ConsultasHoje = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ConsultasHoje.setGeometry(QtCore.QRect(380, 510, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ConsultasHoje.setFont(font)
        self.pushButton_ConsultasHoje.setStyleSheet("")
        self.pushButton_ConsultasHoje.setObjectName("pushButton_ConsultasHoje")
        self.pushButton_TodasConsultas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TodasConsultas.setGeometry(QtCore.QRect(520, 510, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TodasConsultas.setFont(font)
        self.pushButton_TodasConsultas.setStyleSheet("")
        self.pushButton_TodasConsultas.setObjectName("pushButton_TodasConsultas")
        self.dateTimeEdit_Consultas2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_Consultas2.setGeometry(QtCore.QRect(223, 510, 151, 22))
        self.dateTimeEdit_Consultas2.setStyleSheet("")
        self.dateTimeEdit_Consultas2.setObjectName("dateTimeEdit_Consultas2")
        self.dateTimeEdit_Consultas1 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_Consultas1.setGeometry(QtCore.QRect(70, 510, 151, 22))
        self.dateTimeEdit_Consultas1.setStyleSheet("")
        self.dateTimeEdit_Consultas1.setObjectName("dateTimeEdit_Consultas1")
        self.label_FiltroData = QtWidgets.QLabel(self.centralwidget)
        self.label_FiltroData.setGeometry(QtCore.QRect(30, 510, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_FiltroData.setFont(font)
        self.label_FiltroData.setStyleSheet("")
        self.label_FiltroData.setObjectName("label_FiltroData")
        self.pushButton_Stock = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stock.setGeometry(QtCore.QRect(660, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stock.setFont(font)
        self.pushButton_Stock.setStyleSheet("")
        self.pushButton_Stock.setObjectName("pushButton_Stock")
        self.pushButton_NovaReceita = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_NovaReceita.setGeometry(QtCore.QRect(660, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_NovaReceita.setFont(font)
        self.pushButton_NovaReceita.setStyleSheet("")
        self.pushButton_NovaReceita.setObjectName("pushButton_NovaReceita")
        self.pushButton_Receitas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Receitas.setGeometry(QtCore.QRect(660, 430, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Receitas.setFont(font)
        self.pushButton_Receitas.setStyleSheet("")
        self.pushButton_Receitas.setObjectName("pushButton_Receitas")
        MainWindow_Medicos.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Medicos)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Medicos.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Medicos)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Medicos)

    def retranslateUi(self, MainWindow_Medicos):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Medicos.setWindowTitle(_translate("MainWindow_Medicos", "MainWindow"))
        self.label_NomeUtilizador.setText(_translate("MainWindow_Medicos", "Nome"))
        self.label_Consultas.setText(_translate("MainWindow_Medicos", "Consultas de Hoje :"))
        self.pushButton_ConcluirConsulta.setText(_translate("MainWindow_Medicos", "Concluir Consulta"))
        self.pushButton_AdiarConsulta.setText(_translate("MainWindow_Medicos", "Adiar Consulta"))
        self.pushButton_RemoverConsulta.setText(_translate("MainWindow_Medicos", "Remover Consulta"))
        self.pushButton_ConsultasHoje.setText(_translate("MainWindow_Medicos", "Consultas de hoje"))
        self.pushButton_TodasConsultas.setText(_translate("MainWindow_Medicos", "Todas as Consultas"))
        self.label_FiltroData.setText(_translate("MainWindow_Medicos", "Entre:"))
        self.pushButton_Stock.setText(_translate("MainWindow_Medicos", "Stock"))
        self.pushButton_NovaReceita.setText(_translate("MainWindow_Medicos", "Nova Receita"))
        self.pushButton_Receitas.setText(_translate("MainWindow_Medicos", "Receitas"))
