# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Almeida\Desktop\Trabalhos\hospital-app\UI\medicos\AdicionarMedicamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAdicionarMedicamento(object):
    def setupUi(self, FormAdicionarMedicamento):
        FormAdicionarMedicamento.setObjectName("FormAdicionarMedicamento")
        FormAdicionarMedicamento.resize(400, 400)
        FormAdicionarMedicamento.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"        border: 2px solid #366abf;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #366abf;\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color:white;\n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:white;\n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QPlainTextEdit{\n"
"background-color:white;\n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QWidget{\n"
"background-color: white;\n"
"\n"
"}")
        self.label_Medicamento = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_Medicamento.setGeometry(QtCore.QRect(30, 30, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Medicamento.setFont(font)
        self.label_Medicamento.setObjectName("label_Medicamento")
        self.comboBox_Medicamentos = QtWidgets.QComboBox(FormAdicionarMedicamento)
        self.comboBox_Medicamentos.setGeometry(QtCore.QRect(30, 60, 331, 31))
        self.comboBox_Medicamentos.setObjectName("comboBox_Medicamentos")
        self.label_DataInicio = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_DataInicio.setGeometry(QtCore.QRect(30, 120, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_DataInicio.setFont(font)
        self.label_DataInicio.setObjectName("label_DataInicio")
        self.dateEdit_DataInicio = QtWidgets.QDateEdit(FormAdicionarMedicamento)
        self.dateEdit_DataInicio.setGeometry(QtCore.QRect(30, 140, 151, 22))
        self.dateEdit_DataInicio.setObjectName("dateEdit_DataInicio")
        self.label_DataFim = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_DataFim.setGeometry(QtCore.QRect(210, 120, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_DataFim.setFont(font)
        self.label_DataFim.setObjectName("label_DataFim")
        self.dateEdit_DataFim = QtWidgets.QDateEdit(FormAdicionarMedicamento)
        self.dateEdit_DataFim.setGeometry(QtCore.QRect(210, 140, 151, 22))
        self.dateEdit_DataFim.setObjectName("dateEdit_DataFim")
        self.label_Observacoes = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_Observacoes.setGeometry(QtCore.QRect(30, 190, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_Observacoes.setFont(font)
        self.label_Observacoes.setObjectName("label_Observacoes")
        self.plainTextEdit_Observacoes = QtWidgets.QPlainTextEdit(FormAdicionarMedicamento)
        self.plainTextEdit_Observacoes.setGeometry(QtCore.QRect(30, 210, 331, 81))
        self.plainTextEdit_Observacoes.setObjectName("plainTextEdit_Observacoes")
        self.pushButton_Adicionar = QtWidgets.QPushButton(FormAdicionarMedicamento)
        self.pushButton_Adicionar.setGeometry(QtCore.QRect(280, 320, 81, 31))
        self.pushButton_Adicionar.setObjectName("pushButton_Adicionar")
        self.pushButton_Cancelar = QtWidgets.QPushButton(FormAdicionarMedicamento)
        self.pushButton_Cancelar.setGeometry(QtCore.QRect(180, 320, 81, 31))
        self.pushButton_Cancelar.setObjectName("pushButton_Cancelar")

        self.retranslateUi(FormAdicionarMedicamento)
        QtCore.QMetaObject.connectSlotsByName(FormAdicionarMedicamento)

    def retranslateUi(self, FormAdicionarMedicamento):
        _translate = QtCore.QCoreApplication.translate
        FormAdicionarMedicamento.setWindowTitle(_translate("FormAdicionarMedicamento", "Adicionar Medicamento"))
        self.label_Medicamento.setText(_translate("FormAdicionarMedicamento", "Medicamento:"))
        self.label_DataInicio.setText(_translate("FormAdicionarMedicamento", "Data Início:"))
        self.label_DataFim.setText(_translate("FormAdicionarMedicamento", "Data Fim:"))
        self.label_Observacoes.setText(_translate("FormAdicionarMedicamento", "Observações:"))
        self.pushButton_Adicionar.setText(_translate("FormAdicionarMedicamento", "Adicionar"))
        self.pushButton_Cancelar.setText(_translate("FormAdicionarMedicamento", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAdicionarMedicamento = QtWidgets.QWidget()
    ui = Ui_FormAdicionarMedicamento()
    ui.setupUi(FormAdicionarMedicamento)
    FormAdicionarMedicamento.show()
    sys.exit(app.exec_())
