# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/medicos/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Login(object):
    def setupUi(self, MainWindow_Login):
        MainWindow_Login.setObjectName("MainWindow_Login")
        MainWindow_Login.setEnabled(True)
        MainWindow_Login.resize(400, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow_Login)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: black;\n"
"    border-radius: 10px;       \n"
"    border: 2px solid #366abf;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #366abf;\n"
"}\n"
"\n"
"QDateTimeEdit{\n"
"background-color:white; \n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QTableView{\n"
" border: 2px solid #366abf; /* Espessura, Estilo (solid/dashed/dotted) e Cor */\n"
"    border-radius: 5px;       /* Cantos arredondados */\n"
"    gridline-color: #dcdcdc;   /* Cor das linhas que separam as células */\n"
"    background-color: white;\n"
"    selection-background-color: lightblue; /* Cor da linha quando selecionada */\n"
"}\n"
"\n"
"QLCDNumber{\n"
"border: 2px solid #366abf;\n"
"border-radius: 10px;\n"
"}\n"
"QWidget{\n"
"background-color: white;\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.relogioLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.relogioLCD.setGeometry(QtCore.QRect(480, 510, 64, 23))
        self.relogioLCD.setObjectName("relogioLCD")
        self.label_Utilizador = QtWidgets.QLabel(self.centralwidget)
        self.label_Utilizador.setGeometry(QtCore.QRect(60, 260, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Utilizador.setFont(font)
        self.label_Utilizador.setObjectName("label_Utilizador")
        self.lineEdit_Utilizador = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Utilizador.setGeometry(QtCore.QRect(60, 290, 291, 20))
        self.lineEdit_Utilizador.setObjectName("lineEdit_Utilizador")
        self.label_Passe = QtWidgets.QLabel(self.centralwidget)
        self.label_Passe.setGeometry(QtCore.QRect(60, 340, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Passe.setFont(font)
        self.label_Passe.setObjectName("label_Passe")
        self.lineEdit_Passe = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Passe.setGeometry(QtCore.QRect(60, 370, 291, 20))
        self.lineEdit_Passe.setObjectName("lineEdit_Passe")
        self.pushButton_Entrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Entrar.setGeometry(QtCore.QRect(170, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Entrar.setFont(font)
        self.pushButton_Entrar.setObjectName("pushButton_Entrar")
        self.label_LoginTitulo = QtWidgets.QLabel(self.centralwidget)
        self.label_LoginTitulo.setGeometry(QtCore.QRect(50, 80, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_LoginTitulo.setFont(font)
        self.label_LoginTitulo.setObjectName("label_LoginTitulo")
        MainWindow_Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Login)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Login.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Login)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Login)

    def retranslateUi(self, MainWindow_Login):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Login.setWindowTitle(_translate("MainWindow_Login", "MainWindow"))
        self.label_Utilizador.setText(_translate("MainWindow_Login", "Utilizador :"))
        self.label_Passe.setText(_translate("MainWindow_Login", "Palavra-Passe :"))
        self.pushButton_Entrar.setText(_translate("MainWindow_Login", "Entrar"))
        self.label_LoginTitulo.setText(_translate("MainWindow_Login", "Bem-Vindo!"))
