# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Almeida\Desktop\Trabalhos\hospital-app\UI\medicos\NovaReceita.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNovaReceita(object):
    def setupUi(self, FormNovaReceita):
        FormNovaReceita.setObjectName("FormNovaReceita")
        FormNovaReceita.resize(600, 500)
        FormNovaReceita.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"        color: black;\n"
"        border-radius: 10px;\n"
"        border: 2px solid #366abf;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #366abf;\n"
"}\n"
"\n"
"QDateTimeEdit{\n"
"background-color:white;\n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QTableView, QTableWidget{\n"
" border: 2px solid #366abf; /* Espessura, Estilo (solid/dashed/dotted) e Cor */ \n"
"    border-radius: 5px;       /* Cantos arredondados */\n"
"    gridline-color: #dcdcdc;   /* Cor das linhas que separam as celulas */      \n"
"    background-color: white;\n"
"    selection-background-color: lightblue; /* Cor da linha quando selecionada */\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:white;\n"
"color: black;\n"
"border: 2px solid #366abf;\n"
"}\n"
"\n"
"QWidget{\n"
"background-color: white;\n"
"\n"
"}")
        self.label_Titulo = QtWidgets.QLabel(FormNovaReceita)
        self.label_Titulo.setGeometry(QtCore.QRect(20, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Titulo.setFont(font)
        self.label_Titulo.setObjectName("label_Titulo")
        self.label_IdUtente = QtWidgets.QLabel(FormNovaReceita)
        self.label_IdUtente.setGeometry(QtCore.QRect(30, 80, 90, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_IdUtente.setFont(font)
        self.label_IdUtente.setObjectName("label_IdUtente")
        self.lineEdit_IdUtente = QtWidgets.QLineEdit(FormNovaReceita)
        self.lineEdit_IdUtente.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.lineEdit_IdUtente.setReadOnly(True)
        self.lineEdit_IdUtente.setObjectName("lineEdit_IdUtente")
        self.label_IdConsulta = QtWidgets.QLabel(FormNovaReceita)
        self.label_IdConsulta.setGeometry(QtCore.QRect(320, 80, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_IdConsulta.setFont(font)
        self.label_IdConsulta.setObjectName("label_IdConsulta")
        self.lineEdit_IdConsulta = QtWidgets.QLineEdit(FormNovaReceita)
        self.lineEdit_IdConsulta.setGeometry(QtCore.QRect(440, 80, 113, 20))
        self.lineEdit_IdConsulta.setReadOnly(True)
        self.lineEdit_IdConsulta.setObjectName("lineEdit_IdConsulta")
        self.tableWidget_Medicamentos = QtWidgets.QTableWidget(FormNovaReceita)
        self.tableWidget_Medicamentos.setGeometry(QtCore.QRect(30, 170, 531, 221))
        self.tableWidget_Medicamentos.setObjectName("tableWidget_Medicamentos")
        self.tableWidget_Medicamentos.setColumnCount(5)
        self.tableWidget_Medicamentos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Medicamentos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Medicamentos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Medicamentos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Medicamentos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Medicamentos.setHorizontalHeaderItem(4, item)
        self.label_ListaMedicamentos = QtWidgets.QLabel(FormNovaReceita)
        self.label_ListaMedicamentos.setGeometry(QtCore.QRect(30, 140, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ListaMedicamentos.setFont(font)
        self.label_ListaMedicamentos.setObjectName("label_ListaMedicamentos")
        self.pushButton_AdicionarMedicamento = QtWidgets.QPushButton(FormNovaReceita)
        self.pushButton_AdicionarMedicamento.setGeometry(QtCore.QRect(380, 130, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_AdicionarMedicamento.setFont(font)
        self.pushButton_AdicionarMedicamento.setObjectName("pushButton_AdicionarMedicamento")
        self.pushButton_Gravar = QtWidgets.QPushButton(FormNovaReceita)
        self.pushButton_Gravar.setGeometry(QtCore.QRect(440, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Gravar.setFont(font)
        self.pushButton_Gravar.setObjectName("pushButton_Gravar")
        self.pushButton_Cancelar = QtWidgets.QPushButton(FormNovaReceita)
        self.pushButton_Cancelar.setGeometry(QtCore.QRect(30, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cancelar.setFont(font)
        self.pushButton_Cancelar.setObjectName("pushButton_Cancelar")

        self.retranslateUi(FormNovaReceita)
        QtCore.QMetaObject.connectSlotsByName(FormNovaReceita)

    def retranslateUi(self, FormNovaReceita):
        _translate = QtCore.QCoreApplication.translate
        FormNovaReceita.setWindowTitle(_translate("FormNovaReceita", "Nova Receita"))
        self.label_Titulo.setText(_translate("FormNovaReceita", "Nova Receita"))
        self.label_IdUtente.setText(_translate("FormNovaReceita", "ID do Utente:"))
        self.label_IdConsulta.setText(_translate("FormNovaReceita", "ID da Consulta:"))
        item = self.tableWidget_Medicamentos.horizontalHeaderItem(0)
        item.setText(_translate("FormNovaReceita", "Medicamento"))
        item = self.tableWidget_Medicamentos.horizontalHeaderItem(1)
        item.setText(_translate("FormNovaReceita", "Data Início"))
        item = self.tableWidget_Medicamentos.horizontalHeaderItem(2)
        item.setText(_translate("FormNovaReceita", "Data Fim"))
        item = self.tableWidget_Medicamentos.horizontalHeaderItem(3)
        item.setText(_translate("FormNovaReceita", "Observações"))
        item = self.tableWidget_Medicamentos.horizontalHeaderItem(4)
        item.setText(_translate("FormNovaReceita", "ID Medicamento"))
        self.label_ListaMedicamentos.setText(_translate("FormNovaReceita", "Lista de Medicamentos:"))
        self.pushButton_AdicionarMedicamento.setText(_translate("FormNovaReceita", "Adicionar Medicamento"))
        self.pushButton_Gravar.setText(_translate("FormNovaReceita", "Gravar Receita"))
        self.pushButton_Cancelar.setText(_translate("FormNovaReceita", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormNovaReceita = QtWidgets.QWidget()
    ui = Ui_FormNovaReceita()
    ui.setupUi(FormNovaReceita)
    FormNovaReceita.show()
    sys.exit(app.exec_())
