# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Almeida\Desktop\Trabalhos\hospital-app\UI\medicos\AdicionarMedicamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_FormAdicionarMedicamento(object):
    def setupUi(self, FormAdicionarMedicamento):
        FormAdicionarMedicamento.setObjectName("FormAdicionarMedicamento")
        FormAdicionarMedicamento.resize(400, 400)
        FormAdicionarMedicamento.setWindowIcon(QtGui.QIcon(os.path.join(os.path.dirname(__file__), "imagens", "logo.png")))
        FormAdicionarMedicamento.setStyleSheet("""
/* === OmniCare Hospital Theme === */
QWidget {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #E8F4F8, stop:1 #F0F8FF);
    font-family: 'Segoe UI', Arial;
}

QPushButton {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0D7377, stop:1 #14919B);
    color: white;
    border-radius: 12px;
    border: none;
    padding: 8px 16px;
    font-weight: bold;
}

QPushButton:hover {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #14919B, stop:1 #0D7377);
}

QLabel {
    color: #0D7377;
    background: transparent;
}

QDateEdit {
    background-color: white;
    color: #2C3E50;
    border: 2px solid #B8D4E3;
    border-radius: 8px;
    padding: 2px 6px;
    min-height: 26px;
}

QComboBox {
    background-color: white;
    color: #2C3E50;
    border: 2px solid #B8D4E3;
    border-radius: 8px;
    padding: 5px;
}

QPlainTextEdit {
    background-color: white;
    color: #2C3E50;
    border: 2px solid #B8D4E3;
    border-radius: 8px;
}

QComboBox:focus, QDateEdit:focus, QPlainTextEdit:focus {
    border: 2px solid #14919B;
}
""")
        self.label_Medicamento = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_Medicamento.setGeometry(QtCore.QRect(30, 30, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Medicamento.setFont(font)
        self.label_Medicamento.setObjectName("label_Medicamento")
        self.comboBox_Medicamentos = QtWidgets.QComboBox(FormAdicionarMedicamento)
        self.comboBox_Medicamentos.setGeometry(QtCore.QRect(30, 60, 331, 31))
        self.comboBox_Medicamentos.setObjectName("comboBox_Medicamentos")
        self.label_DataInicio = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_DataInicio.setGeometry(QtCore.QRect(30, 120, 110, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_DataInicio.setFont(font)
        self.label_DataInicio.setObjectName("label_DataInicio")
        self.dateEdit_DataInicio = QtWidgets.QDateEdit(FormAdicionarMedicamento)
        self.dateEdit_DataInicio.setGeometry(QtCore.QRect(30, 140, 151, 28))
        self.dateEdit_DataInicio.setObjectName("dateEdit_DataInicio")
        self.label_DataFim = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_DataFim.setGeometry(QtCore.QRect(210, 120, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_DataFim.setFont(font)
        self.label_DataFim.setObjectName("label_DataFim")
        self.dateEdit_DataFim = QtWidgets.QDateEdit(FormAdicionarMedicamento)
        self.dateEdit_DataFim.setGeometry(QtCore.QRect(210, 140, 151, 28))
        self.dateEdit_DataFim.setObjectName("dateEdit_DataFim")
        self.label_Observacoes = QtWidgets.QLabel(FormAdicionarMedicamento)
        self.label_Observacoes.setGeometry(QtCore.QRect(30, 190, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_Observacoes.setFont(font)
        self.label_Observacoes.setObjectName("label_Observacoes")
        self.plainTextEdit_Observacoes = QtWidgets.QPlainTextEdit(FormAdicionarMedicamento)
        self.plainTextEdit_Observacoes.setGeometry(QtCore.QRect(30, 210, 331, 81))
        self.plainTextEdit_Observacoes.setObjectName("plainTextEdit_Observacoes")
        self.pushButton_Adicionar = QtWidgets.QPushButton(FormAdicionarMedicamento)
        self.pushButton_Adicionar.setGeometry(QtCore.QRect(280, 320, 81, 31))
        self.pushButton_Adicionar.setObjectName("pushButton_Adicionar")
        self.pushButton_Cancelar = QtWidgets.QPushButton(FormAdicionarMedicamento)
        self.pushButton_Cancelar.setGeometry(QtCore.QRect(180, 320, 81, 31))
        self.pushButton_Cancelar.setObjectName("pushButton_Cancelar")

        self.retranslateUi(FormAdicionarMedicamento)
        QtCore.QMetaObject.connectSlotsByName(FormAdicionarMedicamento)

    def retranslateUi(self, FormAdicionarMedicamento):
        _translate = QtCore.QCoreApplication.translate
        FormAdicionarMedicamento.setWindowTitle(_translate("FormAdicionarMedicamento", "OmniCare - Adicionar Medicamento"))
        self.label_Medicamento.setText(_translate("FormAdicionarMedicamento", "Medicamento:"))
        self.label_DataInicio.setText(_translate("FormAdicionarMedicamento", "Data Início:"))
        self.label_DataFim.setText(_translate("FormAdicionarMedicamento", "Data Fim:"))
        self.label_Observacoes.setText(_translate("FormAdicionarMedicamento", "Observações:"))
        self.pushButton_Adicionar.setText(_translate("FormAdicionarMedicamento", "Adicionar"))
        self.pushButton_Cancelar.setText(_translate("FormAdicionarMedicamento", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAdicionarMedicamento = QtWidgets.QWidget()
    ui = Ui_FormAdicionarMedicamento()
    ui.setupUi(FormAdicionarMedicamento)
    FormAdicionarMedicamento.show()
    sys.exit(app.exec_())
